odrive_0:
  ros__parameters:
    node_id: 0
    control_mode: 0x2
    input_mode: 0x2
    velocity_limit: 20000.0
    current_limit: 23.44
    traj_vel_limit: 20000.0
    traj_accel_limit: 2000.0
    traj_decel_limit: 2000.0
    traj_inertia: 200.0
odrive_1:
  ros__parameters:
    node_id: 1
    control_mode: 0x2
    input_mode: 0x2
    velocity_limit: 20000.0
    current_limit: 23.44
    traj_vel_limit: 20000.0
    traj_accel_limit: 2000.0
    traj_decel_limit: 2000.0
    traj_inertia: 200.0
odrive_2:
  ros__parameters:
    node_id: 2
    control_mode: 0x2
    input_mode: 0x2
    velocity_limit: 20000.0
    current_limit: 23.44
    traj_vel_limit: 20000.0
    traj_accel_limit: 2000.0
    traj_decel_limit: 2000.0
    traj_inertia: 200.0
odrive_3:
  ros__parameters:
    node_id: 3
    control_mode: 0x2
    input_mode: 0x2
    velocity_limit: 20000.0
    current_limit: 23.44
    traj_vel_limit: 20000.0
    traj_accel_limit: 2000.0
    traj_decel_limit: 2000.0
    traj_inertia: 200.0
socket_can_sender:
  ros__parameters:
    interface: can0
    timeout_sec: 0.01
socket_can_reciver:
  ros__parameters:
    interface: can0
    timeout_sec: 0.01
lifecycle_manager:
  ros__parameters:
    autostart: true
    node_names: ['socket_can_sender', 'socket_can_receiver', 'odrive_0', 'odrive_1', 'odrive_2', 'odrive_3']
    bond_timeout: 4.0
    attempt_respawn_reconnection: true
    bond_respawn_max_duration: 10.0    

